pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                echo 'Building..'
		./mvnw clean install
            }
        }
        stage('Test') {
            steps {
                echo 'Testing..'
		mvn clean test
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying....'
            }
        }
    }
}
